### ISSUE TITLE
game name ideas?

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/ludum_dare_51#15]

**Comment by avivajpeyi** [comment]
Sleepy Steve? I thought the game idea could be that "steve" is dreaming about being in a dungeon. If the player 'dies' then Steve wakes up...

**Comment by alishanpremani** [comment]
Hmm... Race Against Time might be too cliche. Maybe: Survive the Second Time <- get it?

**Comment by alishanpremani** [comment]
OR
https://en.wikipedia.org/wiki/Ten_Seconds_to_Hell

**Comment by avivajpeyi** [comment]
ooo i like these!
