### ISSUE TITLE
Create particle explosion effect when laser/missile hits anything

### ISSUE THREAD

**Issue by alishanpremani** [avivajpeyi/ludum_dare_51#20]
Different effect for laser vs missile

**Comment by avivajpeyi** [comment]
For the laser we can use the Bot's spark effect
<img width="166" alt="Screen Shot 2022-10-04 at 4 31 54 pm" src="https://user-images.githubusercontent.com/15642823/193742024-5e1ccf0c-3acd-49ea-8018-531eaf828438.png">


For the missile we will need to make a new one, maybe using the following:
https://www.youtube.com/watch?v=dOnQY0t3TBM

<img width="390" alt="Screen Shot 2022-10-04 at 4 33 13 pm" src="https://user-images.githubusercontent.com/15642823/193742123-c31a99ea-a670-400f-bb3d-2ca2ea076ac3.png">
