### ISSUE TITLE
Fix turret rotation

### ISSUE THREAD

**Issue by alishanpremani** [avivajpeyi/ludum_dare_51#21]

**Comment by avivajpeyi** [comment]
Currently this is what the turrets look like.
The "start angle" is marked with the blue line.
The "target angle" is marked with the red line.
The "base"/ range of the target angle is marked with the green line.
<img width="540" alt="current" src="https://user-images.githubusercontent.com/15642823/193717513-8b5c6cff-b75b-4320-ae6e-6ea425b3b29e.png">


We want the start angle to always be perpendicular to the base.
We want the target angle to always be with the range marked by the green line (so turret shaft never rotates below the base)

<img width="540" alt="what_we_want" src="https://user-images.githubusercontent.com/15642823/193717537-258c8065-8f3b-4d0e-b4ab-79eaeb396c15.png">

**Comment by alishanpremani** [comment]
Fixed. Red lines are aligned to base. Also, now turrets do not fire when player not in sight.
