### ISSUE TITLE
Code up a enemy gun 

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/ludum_dare_51#7]
Use "Spike" code

**Comment by alishanpremani** [comment]
Laser has been coded. Working now on turret, firing modes, animations, and visual effects in that order.

**Comment by alishanpremani** [comment]
laser now can shoot in two modes. One straight in the -i direction (can be changed to +i, +j,-j, etc.) and one in the direction of the person. The monster also rotates, as well as the direction of the laser.
These modes are not working together in an if statement with the aimStraight and aimAtPerson bools (Ive left comments in Monster.cs and EnemyLaser.cs describing the issue). See if you can take a look, please?

**Comment by avivajpeyi** [comment]
Made some progress -- figured out how to get the turret 'shaft' to rotate instead of the entire body. 

The rotation is not quite lining up (see the blue turrets' and where they are pointing)

We should restrict the rotation to be +-90 deg (where 0 is the center)

Added a 'homing missile' 

<img width="631" alt="Screen Shot 2022-10-04 at 3 41 37 am" src="https://user-images.githubusercontent.com/15642823/193632687-24c94201-9f9a-4f64-962e-f5a4964e2f56.png">
